# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/litany',
                'doc_host': 'https://fenke.github.io',
                'git_url': 'https://github.com/fenke/litany',
                'lib_path': 'litany'},
  'syms': {'litany.core': {'litany.core.foo': ('core.html#foo', 'litany/core.py')}}}
